services:
  Angular_Introduction:
    container_name: Angular_Introduction
    image: angular_introduction
    ports:
      - 127.0.0.1:80:80
    networks:
      - sample-network
  
  Flask_Introduction:
    container_name: Flask_Introduction
    image: flask_introduction
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - sample-network

networks:
  sample-network:
    name: sample-network
